### ISSUE TITLE
English Block

### ISSUE THREAD

**Issue by enemali** [VubbiScript/VubbiScript#12]
When will the english version be availbe or how can one translate the blocks to english?

**Comment by jeroenpx** [comment]
Hello enemali,
Good to know you are interested.
I am currently working on translating everything to English. I recently finished the translation of the website & documentation. Next step is the software itself.

Depending on how much of my spare time I can spend on this project, an English translation will probably be available in a month or two. Would that be ok for you?
After I finished the translation to English, translating to more languages should also be a lot easier.

**Comment by enemali** [comment]
> English translation will probably be available in a month or two. Would that be ok for you?
Yes I'm OK with the time and i will patiently wait for it . Kindly update us here when you're done with the English translation of the software .
Thank you for this wonderful software

**Comment by HerelAdrastel** [comment]
Hi, I've also discovered this software and it is so awesome. I hope the english version will be available soon ! You've made such a wonderful work !

**Comment by jeroenpx** [comment]
Hello @HerelAdrastel, @enemali,
Thanks!! Posts like this really help to keep me motivated! And so...

Today I released version 0.5.0 of VubbiScript which is available in English!
You can find it on the website: https://vubbiscript.github.io/en/getting-started/.

Enjoy!

**Comment by enemali** [comment]
wow , keep it  up
