### ISSUE TITLE
Block editor doesn't work in Edge

### ISSUE THREAD

**Issue by kurtdevocht** [VubbiScript/VubbiScript#13]
When Edge is the default browser, the block-editor doesn't show the script (keeps on showing 'Loading...')

**Comment by jeroenpx** [comment]
Hello Kurt,

This is fixed now. VubbiScript works on Edge. It was actually already fixed for a couple of versions of VubbiScript but the example projects on the website were still using the old version of VubbiScript. I updated the example projects now to come with the latest version.

Kind regards,
Jeroen
